// The "Pourquoi cette note ?" pedagogical breakdown (Étape 4) for a guest
// review already generated by lib/clients/guestReviewEngine.js. Rereads
// the exact same real signals that engine's own ratingOf() weighs
// (hotel condition, open incidents, reputation, eco bonus, season-event
// noise -- lib/maintenance/maintenanceCostEngine.js/incidentImpact.js,
// lib/expansion/majorProjectsEngine.js, lib/seasonEvents/
// seasonEventEngine.js, every one of them already exported and pure) --
// never recomputes the rating itself, only explains it after the fact.
// No rng, no new state.
import { safeArray, safeNumber, safeObject } from "../safe.js";
import { hotelCondition } from "../maintenance/maintenanceCostEngine";
import { openIncidents } from "../maintenance/incidentImpact";
import { ecoRatingBonus } from "../expansion/majorProjectsEngine";
import { satisfactionPenaltyForStay } from "../seasonEvents/seasonEventEngine";

const CONDITION_CONCEPT = "Standing perçu";
const ROTATION_CONCEPT = "Temps de rotation des chambres";
const REPUTATION_CONCEPT = "Effet de réputation";
const ECO_CONCEPT = "Positionnement RSE";
const NOISE_CONCEPT = "Qualité de séjour perçue";

// { positives: [string, string?], negatives: [string, string?], businessConcept }
// -- at most two of each, the most significant real factor first; a
// businessConcept is only ever attached to a real factor, never invented.
export function explainReview(review, { hotelState, reservation } = {}) {
  const state = safeObject(hotelState);
  const positives = [];
  const negatives = [];
  let businessConcept = null;

  const condition = hotelCondition(state);
  if (condition >= 90) {
    positives.push("L'excellent état général de l'hôtel");
    businessConcept = businessConcept || CONDITION_CONCEPT;
  } else if (condition < 60) {
    negatives.push("Un entretien général en retrait");
    businessConcept = businessConcept || CONDITION_CONCEPT;
  }

  const unresolvedIncidents = openIncidents(state).filter((incident) => (incident.daysOpen || 0) >= 1);
  if (unresolvedIncidents.length > 0) {
    negatives.push("Une panne non réparée pendant le séjour");
    businessConcept = businessConcept || ROTATION_CONCEPT;
  }

  const eco = ecoRatingBonus(state);
  if (eco > 0) {
    positives.push("La démarche écoresponsable de l'établissement");
    businessConcept = businessConcept || ECO_CONCEPT;
  }

  const reputation = safeNumber(safeObject(safeObject(state.progression).player).reputation, 60);
  if (reputation < 40) {
    negatives.push("Une réputation en retrait qui a pesé sur les attentes");
    businessConcept = businessConcept || REPUTATION_CONCEPT;
  }

  if (reservation && satisfactionPenaltyForStay(reservation) > 0) {
    negatives.push("Des nuisances liées à des travaux en cours pendant le séjour");
    businessConcept = businessConcept || NOISE_CONCEPT;
  }

  if (review?.profile === "vip" && review?.praise) {
    positives.push("Les attentions personnalisées reçues pendant le séjour");
  }

  // No individual factor stood out -- fall back to the rating itself
  // rather than showing an empty breakdown.
  if (positives.length === 0 && negatives.length === 0) {
    if (safeNumber(review?.rating, 3) >= 4) positives.push("Un séjour sans accroc particulier");
    else if (safeNumber(review?.rating, 3) <= 2) negatives.push("Un séjour en retrait, sans cause isolée dominante");
  }

  return { positives: positives.slice(0, 2), negatives: negatives.slice(0, 2), businessConcept };
}

// Which of today's posted reviews (lib/dashboard/dailyReview.js's own
// `guestReviews.posted`) is worth featuring in the evening Journal: the
// most extreme one (furthest from a neutral 3 stars) is the one most
// worth explaining, a V.I.P. breaking ties. Null when nobody posted today.
export function featuredReviewOf(postedReviews) {
  const list = safeArray(postedReviews);
  if (list.length === 0) return null;
  return list
    .slice()
    .sort((a, b) => {
      const extremity = Math.abs(safeNumber(b.rating, 3) - 3) - Math.abs(safeNumber(a.rating, 3) - 3);
      if (extremity !== 0) return extremity;
      return (b.profile === "vip" ? 1 : 0) - (a.profile === "vip" ? 1 : 0);
    })[0];
}

const guestReviewsEngine = { explainReview, featuredReviewOf };
export default guestReviewsEngine;
